### ISSUE TITLE
Unable to paste screenshot from clipboard anymore.

### ISSUE THREAD

**Issue by BerserkeR-Git** [PrivateBin/PrivateBin#1589]
Like the title says, I could swear I could attach a screenshot I have in my clipboard by just pressing ctrl + v in Privatebin, but not anymore.
I'm not sure from which version this behavior started.

It might be better to open an issue on the official PrivateBin repo?

**Comment by elrido** [comment]
Yes, this still worked in 1.7.6, so likely a side-effect of introducing the multi-upload. The error we get in 1.7.8 is:
```
Uncaught TypeError: loadedFiles.map is not a function
    readFileData https://privatebin.net/js/privatebin.js?1.7.8:3283
    addClipboardEventHandler https://privatebin.net/js/privatebin.js?1.7.8:3447
```

**Comment by BerserkeR-Git** [comment]
@elrido when will this fix get into the `privatebin/nginx-fpm-alpine` image because it's still not working for me. Thanks.

**Comment by elrido** [comment]
When we cut a new release - it has not been released yet. It may be a few weeks or months, we don't have a fixed release schedule.

Edit: This has now been released as part of 2.0.0.
